### ISSUE TITLE
ViewSubmission函数报错

### ISSUE THREAD

**Issue by ghost** [mos9527/bilibili-toolman#21]
```python
from bilibili_toolman.bilisession.web import BiliSession
session = BiliSession.from_base64_string(config['misc']['sess_token'])
vs = session.ListSubmittedSubtitles()
va = session.ViewSubmission("BV1rV4y1K7a4")
```
运行到第4行就报错：

> Traceback (most recent call last):
  File "D:\miniconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\miniconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", 
line 430, in main
    run()
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", 
line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path 
    return _run_module_code(code, init_globals, run_name,
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "d:\VSCode\data\extensions\ms-python.python-2022.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code    exec(code, run_globals)
  File "d:\0\BilibiliUploader\test_run_info.py", line 50, in <module>
    va = session.ViewSubmission("BV1rV4y1K7a4")
  File "D:\miniconda3\lib\site-packages\bilibili_toolman\bilisession\web.py", line 236, in ViewSubmission
    arc = self._view_archive(bvid)["data"]
  File "D:\miniconda3\lib\site-packages\bilibili_toolman\bilisession\common\__init__.py", line 19, in wrapper
    return response.json()
  File "D:\miniconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mos9527** [comment]
更新了Web端API，应该不会出现解析错误了
还有，这个接口只能看到自己上传视频的信息，否则是看不到东西的
