### ISSUE TITLE
使用actions投稿无法上传封面图

### ISSUE THREAD

**Issue by ceiminya** [mos9527/bilibili-toolman#28]
输出报错上传封面图失败

```
100%|██████████| 20.0M/20.0M [09:17<00:00, 35.9kB/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/__main__.py", line 6, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 319, in __main__
    result, dirty = upload_sources(sources, arg)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 119, in upload_sources
    video.cover_url = cover_url
                      ^^^^^^^^^
UnboundLocalError: cannot access local variable 'cover_url' where it is not associated with a value
[ 2023-07-29 02:29:34 ClientSession  DEBUG ] MD5: 61950346a81fb2197643de8336cf3cc9
[ 2023-07-29 02:29:34 ClientSession   INFO ] 远端结点： n2307290511yz71ljti7kj1pkir1f2gc
[ 2023-07-29 02:29:34 ClientSession  DEBUG ] 上传完毕： (OK/1 info/Successful.)
[ 2023-07-29 02:29:34 ClientSession  DEBUG ] b1PoTRjctkg.png -> image/png
[ 2023-07-29 02:29:34 ClientSession  DEBUG ] 上传封面图 ([1123752](tel:1123752) B)
[ 2023-07-29 02:29:39  toolman WARNING ] < title : MIXUE (Phonk Remix) | Prod. Marcel NTX , src : https://www.youtube.com/watch?v=b1PoTRjctkg> 上传失败! - 'data' - 重试
[ 2023-07-29 02:29:40 ClientSession  DEBUG ] 上传分块: 10
[ 2023-07-29 02:29:40 ClientSession  DEBUG ] 分块大小: 2097152 B
[ 2023-07-29 02:31:24 ClientSession  DEBUG ] MD5: 61950346a81fb2197643de8336cf3cc9
[ 2023-07-29 02:31:24 ClientSession   INFO ] 远端结点： n23072901160oul75jupu6320b8l0s8x
[ 2023-07-29 02:31:24 ClientSession  DEBUG ] 上传完毕： (OK/1 info/Successful.)
[ 2023-07-29 02:31:24 ClientSession  DEBUG ] b1PoTRjctkg.png -> image/png
[ 2023-07-29 02:31:24 ClientSession  DEBUG ] 上传封面图 ([1123752](tel:1123752) B)
[ 2023-07-29 02:31:32  toolman WARNING ] < title : MIXUE (Phonk Remix) | Prod. Marcel NTX , src : https://www.youtube.com/watch?v=b1PoTRjctkg> 上传失败! - 'data' - 重试
[ 2023-07-29 02:31:33 ClientSession  DEBUG ] 上传分块: 10
[ 2023-07-29 02:31:33 ClientSession  DEBUG ] 分块大小: 2097152 B
[ 2023-07-29 02:31:55 ClientSession WARNING ] 第 1 次重试时：Expecting value: line 1 column 1 (char 0)
[ 2023-07-29 02:33:20 ClientSession  DEBUG ] MD5: 61950346a81fb2197643de8336cf3cc9
[ 2023-07-29 02:33:20 ClientSession   INFO ] 远端结点： n23072906xvaakhya3bo316eolevg3ij
[ 2023-07-29 02:33:20 ClientSession  DEBUG ] 上传完毕： (OK/1 info/Successful.)
[ 2023-07-29 02:33:20 ClientSession  DEBUG ] b1PoTRjctkg.png -> image/png
[ 2023-07-29 02:33:20 ClientSession  DEBUG ] 上传封面图 ([1123752](tel:1123752) B)
[ 2023-07-29 02:33:28  toolman WARNING ] < title : MIXUE (Phonk Remix) | Prod. Marcel NTX , src : https://www.youtube.com/watch?v=b1PoTRjctkg> 上传失败! - 'data' - 重试
[ 2023-07-29 02:33:28 ClientSession  DEBUG ] 上传分块: 10
[ 2023-07-29 02:33:28 ClientSession  DEBUG ] 分块大小: 2097152 B
[ 2023-07-29 02:35:39 ClientSession  DEBUG ] MD5: 61950346a81fb2197643de8336cf3cc9
[ 2023-07-29 02:35:40 ClientSession   INFO ] 远端结点： n2307290339ahcwhwig8ai1jezaujxsv
[ 2023-07-29 02:35:40 ClientSession  DEBUG ] 上传完毕： (OK/1 info/Successful.)
[ 2023-07-29 02:35:40 ClientSession  DEBUG ] b1PoTRjctkg.png -> image/png
[ 2023-07-29 02:35:40 ClientSession  DEBUG ] 上传封面图 ([1123752](tel:1123752) B)
[ 2023-07-29 02:35:44  toolman WARNING ] < title : MIXUE (Phonk Remix) | Prod. Marcel NTX , src : https://www.youtube.com/watch?v=b1PoTRjctkg> 上传失败! - 'data' - 重试
[ 2023-07-29 02:35:45 ClientSession  DEBUG ] 上传分块: 10
[ 2023-07-29 02:35:45 ClientSession  DEBUG ] 分块大小: 2097152 B
[ 2023-07-29 02:37:24 ClientSession  DEBUG ] MD5: 61950346a81fb2197643de8336cf3cc9
[ 2023-07-29 02:37:24 ClientSession   INFO ] 远端结点： n230729052h0xt9f95genc27qa5k986p
[ 2023-07-29 02:37:24 ClientSession  DEBUG ] 上传完毕： (OK/1 info/Successful.)
[ 2023-07-29 02:37:24 ClientSession  DEBUG ] b1PoTRjctkg.png -> image/png
[ 2023-07-29 02:37:24 ClientSession  DEBUG ] 上传封面图 ([1123752](tel:1123752) B)
[ 2023-07-29 02:37:29  toolman WARNING ] < title : MIXUE (Phonk Remix) | Prod. Marcel NTX , src : https://www.youtube.com/watch?v=b1PoTRjctkg> 上传失败! - 'data' - 重试
[ 2023-07-29 02:37:29  toolman   INFO ] 资源已上传
Error: Process completed with exit code 1.
```

**Comment by mos9527** [comment]
可能需要更新登陆凭据
push了更新，现在可以看看具体是什么错误了

**Comment by ceiminya** [comment]
更新完凭据可以用了，还有个问题，用短信验证码登录，凭据一直无法获取，试过好几次了。
```
Traceback (most recent call last):
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 358, in RenewSMSCaptcha
    assert resp.json()["data"]["recaptcha_url"] == ""
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/cli/main.py", line 218, in setup_session
    ret = sess.RenewSMSCaptcha(phone)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 37, in wrapper
    return _classmethod(self, *a, **k)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/common/__init__.py", line 20, in wrapper
    response: Response = classfunc(session, *args, **kwargs)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 364, in RenewSMSCaptcha
    raise RecaptchaRequiredException(data["recaptcha_url"])
bilibili_toolman.bilisession.client.RecaptchaRequiredException: https://www.bilibili.com/h5/project-msg-auth/verify?ct=geetest&recaptcha_token=d73de****&gee_gt=1c0ea****8&gee_challenge=7b286****

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 358, in RenewSMSCaptcha
    assert resp.json()["data"]["recaptcha_url"] == ""
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/__main__.py", line 6, in <module>
    sys.exit(__main__())
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/cli/main.py", line 273, in __main__
    if not setup_session():
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/cli/main.py", line 223, in setup_session
    ret = sess.RenewSMSCaptcha(phone)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 37, in wrapper
    return _classmethod(self, *a, **k)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/common/__init__.py", line 20, in wrapper
    response: Response = classfunc(session, *args, **kwargs)
  File "/home/ceiminya/.local/lib/python3.8/site-packages/bilibili_toolman/bilisession/client.py", line 365, in RenewSMSCaptcha
    raise LoginException(resp, e)
bilibili_toolman.bilisession.common.LoginException: 登陆失败：'NoneType' object is not subscriptable
<Response 200>:{"code":86104,"message":"请使用其它方式注册或登录","ttl":1,"data":null}
```

**Comment by mos9527** [comment]
我这里pass了，看看行不行？

**Comment by ceiminya** [comment]
现在可以了。
