### ISSUE TITLE
GitHub Actions手动转载报错

### ISSUE THREAD

**Issue by ceiminya** [mos9527/bilibili-toolman#32]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/__main__.py", line 6, in <module>
    sys.exit(__main__())
             ^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 273, in __main__
    if not setup_session():
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/cli/main.py", line 241, in setup_session
    sess = BiliSession.from_base64_string(global_args.load)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/web.py", line 623, in from_base64_string
    return BiliSession.from_bytes(b)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/bilibili-toolman/bilibili-toolman/bilibili_toolman/bilisession/web.py", line 607, in from_bytes
    unpickled = pickle.loads(gzip.decompress(b))
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/gzip.py", line 627, in decompress
    if _read_gzip_header(fp) is None:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/gzip.py", line 456, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b',\x85')
```

**Comment by mos9527** [comment]
[Base64编码的session实为gzip压缩后的状态dict](https://github.com/mos9527/bilibili-toolman/blob/master/bilibili_toolman/bilisession/web.py#L599)；这里的错误也许是因为你的session凭据不正确
可以试试重新[准备凭据](https://github.com/mos9527/bilibili-toolman?tab=readme-ov-file#%E5%87%86%E5%A4%87%E5%87%AD%E6%8D%AE)
